package com.glitchstudio.app.effects

/** How a parameter is presented to the user. */
enum class ParamKind { LINEAR, HUE, ANGLE }

/** How a parameter maps to direct finger control on the canvas. */
enum class ParamRole { NONE, POS_X, POS_Y, ANGLE }

/**
 * A single adjustable control for an effect. The [uniform] is the GLSL uniform
 * name (always a `float`) that the renderer feeds [default]..current value into.
 */
data class ShaderParam(
    val name: String,
    val uniform: String,
    val min: Float,
    val max: Float,
    val default: Float,
    /** When true the slider centres on 0 and shows +/- values (Lightroom style). */
    val bipolar: Boolean = false,
    /** Visual style: HUE draws a spectrum track, ANGLE shows degrees. */
    val kind: ParamKind = ParamKind.LINEAR,
    /** Canvas drag mapping for on-image finger control. */
    val role: ParamRole = ParamRole.NONE,
)

enum class EffectCategory(val label: String) {
    COLOR("Color"),
    LIGHT("Light"),
    STYLIZE("Stylize"),
    DISTORT("Distort"),
    GLITCH("Glitch"),
    BLUR("Blur"),
    TEXTURE("Texture"),
    RETRO("Retro"),
}

/**
 * A creative effect backed by a GLSL fragment shader.
 *
 * [fragmentBody] must NOT redeclare the shared uniforms (`u_Texture`,
 * `u_Resolution`, `u_Time`) nor the per-param uniforms — those are generated by
 * [com.glitchstudio.app.gl.ShaderProgram.buildFragmentSource]. The body only
 * declares helper functions and `void main()`, reading `v_TexCoord` (0..1, image
 * upright) and the param uniforms by name.
 *
 * Set [animated] for effects that read `u_Time`; the preview then renders
 * continuously and GIF export sweeps time across frames.
 */
data class ShaderEffect(
    val id: String,
    val name: String,
    val category: EffectCategory,
    val description: String,
    val params: List<ShaderParam>,
    val fragmentBody: String,
    val animated: Boolean = false,
) {
    fun defaultValues(): FloatArray = FloatArray(params.size) { params[it].default }
}
